name: dask_xgboost_slurm

channels:
  - conda-forge
  - defaults

dependencies:
  - bokeh
  - dask=2023.1.1
  - dask-core=2023.1.1
  - dask-jobqueue=0.8.1
  - distributed=2023.1.1
  - h5py
  - hdf5
  - matplotlib
  - numpy
  - pandas
  - patsy
  - pillow
  - pip=22.3.1
  - pytables
  - python
  - scikit-learn
  - scipy
  - six
  - statsmodels
  - xgboost=1.5.2
  - zarr
